#+TITLE: Linum Setup
#+Author: Nils Gustafsson
#+OPTIONS: num:3 toc:nil

This is the file responsible for setting up line numbers correctly, as
part of my init routine. This is a literate =emacs lisp= file, written
in =org-mode=.

* Emacs version

  Native line numbering support was added in =emacs= 26.1, thus we
  only want the =linum= related code in this file if we're on a
  version less than that.


  #+NAME: lit-emacs-init-emacs-version-guard
  #+BEGIN_SRC emacs-lisp +n -r -l ";(%s)" :tangle yes :noweb yes
    ;; Use linum if emacs doesn't have line-numbers yet.
    (eval-when-compile
      (defmacro lit-init-linum-mk-body()
        (if (version<  emacs-version "26.1")
            `(progn
              <<linum-pre-26.1>>                                       ;(preEmacs26)
              )
          `(message "[lit-init-linum] %s"
                    "You've yet to write anything for v26.1+, you dummy!"))))
    (lit-init-linum-mk-body)

  #+END_SRC

  For the body of [[(preEmacs26)][line (preEmacs26)]] see section [[The Solution][The Solution]] below.


* Linum                                                         :pre.v.26:
  :PROPERTIES:
  :header-args: :tangle no
  :END:


  Line numbering minor mode. See the relevant emacs documentation for details.

** The Problem

   WRITTEN: [2018-10-17 ons 12:47]

   I'd like to use ~global-linum-mode~, but it interacts badly with a
   number of different other modes and buffers:

   - Interactive buffers, such as repl buffers and compilation buffers
     may end up becoming exceedingly long. This eventually causes
     =linum= to start to consume unacceptable amounts of system
     resources.

   - Certain other "starred" buffers such as =*Messages*= also exhibit
     this problem.

   - =linum= combined with =pdf-view-mode= exhibits similar problems,
     albeit for different reasons. I forget what those reasons are
     exactly; it's been a while since I looked this up. In any case
     trying to add line numbers to a pdf buffer is a) useless, and b)
     causes *massive* slowdowns.

   And in addition, there are a few modes where it behaves just fine,
   but where I'd like it turned off anyway.

   Sadly there is no built in way to blacklist or exclude certain
   modes from being affected by ~global-linum-mode~. And I don't want
   to have to whitelist every single mode that /does/ work with
   ~global-linum-mode~. Which is also not a thing that's supported in
   the =linum= customize category.

** The Solution

   WRITTEN: [2018-10-17 ons 12:51]

   Since neither whitelisting, nor blacklisting is avaliable directly,
   we'll have implement this functionality manually. The code here is
   based in part on code I found at a now long since dissappeared url[fn:deadlink].

   The idea here is to add the [[(linumDefCustom)][missing customization]] interface
   manually during init, and to then *override* a function called
   =linum-on=.

   [2019-01-12 lör 16:23]

   This solution has become somewhat unreliable after I rewrote some
   of the logic that loads this file. However, I've amended it by also
   overriding the definition of =global-linum-mode=. Seems to work
   again. Hopefully I can stop working on this work-around when I get
   around to upgrading emacs.

   #+NAME: lit-emacs-init-linum-defcustoms
   #+BEGIN_SRC emacs-lisp -n -r -l ";(%s)" :noweb-ref linum-pre-26.1 :noweb yes
     (use-package linum
       :defer t
       :commands (global-linum-mode linum-on)

       ;; Add new customisation options
       :preface
       <<linum-new-defcustoms>>                                     ;(linumDefCustom)

       :config
       ;; Redefine linum-on to respect our new custom
       ;; variables.
       (message "%s %s"
                "from lit-emacs-init-linum:"
                "overriding definition of 'linum-on'...")
       <<linum-on-redef>>                                              ;(linumRedef)

       :hook (after-init . (lambda () (global-linum-mode 1))))
   #+END_SRC

   The new customisation definitions look like this:

   #+NAME: lit-emacs-init-linum-defcustoms
   #+BEGIN_SRC emacs-lisp +n -r -l ";(%s)" :noweb-ref linum-new-defcustoms

     (defcustom global-linum-disabled-modes-list
       '(eshell-mode
         wl-summary-mode
         compilation-mode
         org-mode
         text-mode
         dired-mode
         doc-view-mode
         pdf-view-mode
         haskell-interactive-mode)
       "List of major modes where `global-linum-mode' shouldn't apply."
       :type '(repeat (sexp :tag "Major mode"))
       :tag "Global Linum Mode Major Mode Blacklist"
       :group 'linum)

     (defcustom global-linum-ignore-starred-buffers 't
       "If non-nil, `global-linum-mode' will ignore starred buffers such as *Gnu Emacs*."
       :type 'boolean
       :tag "Global Linum Mode Ignore Starred Buffers"
       :group 'linum)
   #+END_SRC

   And this is the overriding definition of =linum-on=:

   #+NAME: lit-emacs-init-linum-on-redef
   #+BEGIN_SRC emacs-lisp +n -r -l ";(%s)" :noweb-ref linum-on-redef
     (defun my-linum-on ()
       "Activate line-numbers in the current buffer, unless this
     is ruled out by `global-linum-disabled-modes-list'
     `global-linum-ignore-starred-buffers'.

     This function overrides the default definition exported in
     linum.el"
       (unless (or (minibufferp)
                   (member major-mode global-linum-disabled-modes-list)
                   (and global-linum-ignore-starred-buffers
                        (string-match "*" (buffer-name))
                        ))
         (linum-mode 1)))
     (define-globalized-minor-mode my-global-linum-mode linum-mode my-linum-on)

     (advice-add 'linum-on
                 :override
                 #'my-linum-on)

     (advice-add 'global-linum-mode
                 :override
                 #'my-global-linum-mode)

   #+END_SRC


   And that's that. Not too hard to fix, thankfully.


[fn:deadlink] The (now dead) link is:
=https://github.com/Khady/emacs.d/blob/master/setup-linum.el=


* Future Work
  :PROPERTIES:
  :header-args: :noweb no :tangle no
  :END:


** TODO Preserve line numbers when narrowing

   May be able to do something with this code from a SO answer I saw:

   #+BEGIN_SRC emacs-lisp :tangle no

     (require 'linum)

     (defvar my-linum-base-line nil)
     (defvar my-linum-format nil)

     (add-hook 'linum-before-numbering-hook
               (lambda ()
                 (save-excursion
                   (save-restriction
                     (goto-char (point-min))
                     (widen)
                     (setq my-linum-base-line (count-lines 1 (point)))
                     (setq my-linum-format
                           (format "%%%dd"
                                   (length
                                    (int-to-string
                                     (+ my-linum-base-line
                                        (count-lines (point)
                                                     (point-max)))))))))))

     (setq-default linum-format
                   (lambda (line)
                     (format my-linum-format
                             (+ line my-linum-base-line))))

   #+END_SRC

   Got it [[https://emacs.stackexchange.com/questions/24833/preserve-original-line-numbering-for-a-narrowed-region][here]]. The link was valid [2018-10-25 tor 16:45].


   Or maybe not.. It would be confusing, if I ever wanted to use
   =goto-line= in a narrowed buffer.
